###
// GET ALL TODO
GET http://localhost:3000/todo HTTP/1.1     

###
// GET SINGLE TODO
GET http://localhost:3000/todo/62c5df59bd0668e699a2b892 HTTP/1.1

###
// CREATE TODO
POST http://localhost:3000/todo/ HTTP/1.1
Content-Type: application/json

{
    "title": "Chores",
    "description": "Do laundry",
}

###
// UPDATE TODO
PUT http://localhost:3000/todo/ HTTP/1.1
Content-Type: application/json

{
    "id": 6,
    "title": "School",
    "description": "Submit classwork",
    "timestamp": "4pm"
}

###
// DELETE TODO
DELETE http://localhost:3000/todo/ HTTP/1.1
